.storybook/preview.js
docs/Playbook.stories.mdx
docs/Status.stories.mdx
docs/utils.tsx

Adds the version number to the "Playbook" page title. Adds a "current version" badge on the Status page and a link to the GitHub release notes page.
Resolves #51

Chore: Add current version to docs

---

UNRELEASED.md
docs/Forms/TextInput.stories.mdx
docs/Forms/TextInput.stories.tsx
src/components/TextInput/TextInput.module.css
src/components/TextInput/TextInput.tsx

Deprecates the `multiline` prop for the `TextInput` component in favor of  `rows` and `maxRows` in order to to add auto-grow functionality and have control over the visual height of the component. Setting the `rows` prop will switch the input to use a `<textarea>` instead of an `<input>` and an optional `maxRows` prop can control how large the component will expand visually before scrolling the content.
The `multiline` prop is marked as deprecated but will continue to function as if `rows={3}` was passed.
Also added #71 as a future enhancement idea based on feedback from @aChristmasMiracle 
Resolves #69

Feature: Add auto-grow functionality for multiline TextInput

---

UNRELEASED.md
src/components/TextInput/TextInput.module.css

Setting vertical alignment on the `<textarea>` fixes the case of having phantom margin/padding in multiline mode for the `TextInput`.
Fixes #73

Fix: Vertical alignment of TextInput in multiline mode

---

.storybook/preview-head.html

The Typekit reference for the old body font was still in the Playbook docs even though the font wasn't being used. Removing it.

Chore: Remove old typekit reference

---

UNRELEASED.md
docs/Forms/TextInput.stories.mdx
docs/Forms/TextInput.stories.tsx
src/components/TextInput/TextInput.tsx

If the `TextInput` had the `rows` and `maxRows` props set and was either initialized with a value that would cause the input to grow or the user entered a value that caused the input to grow and then the value was cleared, the TextInput wasn't properly resizing back to the initial rows size until the next value change event.
We require the inner ref to fix this, so the method of forwarding the inner ref has changed to use `useImperativeHandle` and expose only the functionality that we'd like to expose on the inner element rather than forwarding the entire element ref. This is also good because it allows us to control what functionality we expose vs just having the entire inner element exposed by ref.

Fix: Make sure TextInput resizes properly when cleared or initialized

---

UNRELEASED.md
docs/Navigation/Link.stories.mdx
docs/Navigation/Link.stories.tsx
src/components/Link/Link.module.css
src/components/Link/Link.tsx
tailwind.preset.js

Occasionally we want to wrap elements in a `<Link>` to provide the correct semantic indication that the action is a navigation change but find ourselves having to either work around the fact that it applies default anchor tag styling to the child elements. This introduces an `unstyled` option that reverses some of those styles to allow for this use-case.
Resolves https://github.com/FieldLevel/FieldLevelPlaybook/issues/68

Feature: Add unstyled option to Link

---

UNRELEASED.md
docs/Overlays/Modal.stories.mdx
docs/Overlays/Modal.stories.tsx
src/components/Modal/Modal.module.css
src/components/Modal/Modal.tsx

Fixes some common frustrations with trying to use the `Modal` component in it's current state. The general issue is that the current default Modal sizing is too restrictive and the `large` variant is too wide. This introduces a handful of changes to the `Modal` component to address these issues:
- The default Modal no longer has a fixed max height and will expand to the max height of the viewport minus some margins.
- The `large` variant max width has been reduced down to the `lg` breakpoint instead of `xl`.
- A `small` variant has been introduced with an `xs` breakpoint max width.
- Modal is now vertically centered in the viewport instead of having a fixed top margin.
Resolves #72

Feature: Make Modal sizing more flexible

---

UNRELEASED.md
docs/Actions/Button.stories.mdx
docs/Actions/Button.stories.tsx
src/components/Button/Button.module.css
src/components/Button/Button.tsx
src/components/Modal/Modal.tsx

This change adds a "secondary" variant to `Button`. We've felt for awhile that our Button is missing a variant that can be more naturally paired with a primary or destructive button. Luckily we already have the color naming and designation for a "secondary" set that we've already used for inputs that makes this an easy add system-wise. This creates the variant and also uses it on `Modal` for the style of the secondary action.

Feature: Add secondary Button variant

---

UNRELEASED.md
docs/Actions/Button.stories.mdx
docs/Actions/Button.stories.tsx
src/components/Button/Button.tsx

This is a quality of life change for something we do a lot with Buttons. Often the action of a button will be to do a navigation change, so if we wanted to be semantically correct the right thing to do would be to wrap the button in an anchor tag, but currently this impacts the styling of the Button that we have to work around or just do a programmatic navigation change which we're trying to move away from as much as possible. With the addition of the `unstyled` option on `Link` we can now handle this properly without impacting the Button style.
Resolves #79

Feature: Add url to Button

---

docs/Forms/Select.stories.mdx
docs/Forms/Select.stories.tsx
src/components/Select/Select.module.css
src/components/Select/Select.tsx

This change makes the `Select` placeholder option available for re-selection instead of being disabled, allowing that decision to be handled at the form/input validation level in the application instead. It also allows the placeholder to be either a `string` or `Option` so that the placeholder value can be used in validation if necessary.
Also fixes a Firefox styling issue due to missing background color style.
Resolves #34 
Resolves #66

Feature: Allow Select placeholder re-select

---

UNRELEASED.md
src/components/Modal/Modal.module.css
src/components/Modal/Modal.tsx

Updates the `Modal` styles for mobile screens to be bit more flexible in use than always being a full-screen takeover like it has been. The changes are as follows:
Small variant stays centered in the viewport sized to the content and grows to the full viewport minus some margins surrounding:
Default variant docks to the bottom of the viewport sized to the content and grows to fill almost the entire viewport:
Large variant remains as a full-screen takeover:

Update mobile Modal variant styles

---

.github/workflows/github-package-publish.yml
.github/workflows/lint-on-pr.yml
UNRELEASED.md
package.json
yarn.lock

Upgrades project dependencies to use React v17.0.2 and build configuration to require Node 18 and Yarn 1.22.19.

Chore: Upgrade to React 17 and Node 18

---

UNRELEASED.md
docs/Forms/TextInput.stories.mdx
docs/Forms/TextInput.stories.tsx
src/components/TextInput/TextInput.module.css
src/components/TextInput/TextInput.tsx

Updates the `forwardRef` behavior for `TextInput` to provide the full ref to the inner `HTMLInputElement` or `HTMLTextAreaElement` instead of our custom imperative handle that previously only exposed the `focus()` functionality. This should not be a breaking change since focus will still work as before.
Additionally removes the `max-height` style on the the input that was preventing any `TextInput` with a `maxRows` higher than 7 from working and removes the previously deprecated `multiline` prop.
Fixes #111 and #99.

Fix issues with TextInput

---

UNRELEASED.md
docs/Actions/Button.stories.mdx
docs/Actions/Button.stories.tsx
docs/Navigation/Link.stories.mdx
docs/Navigation/Link.stories.tsx
src/components/Button/Button.module.css
src/components/Button/Button.tsx
src/components/Link/Link.module.css
src/components/Link/Link.tsx

Fixes a handful of outstanding issues with the `Button` and `Link` components.
- Adds a `forwardRef` to the underlying `<button>` element to make things like focusing a `Button` programmatically possible. Fixes #101 
- Fixes a styling bug when a `Button` has only an `icon` prop and no content. Fixes #104 
- Adds accessibility props to `Button`. Fixes #108 
- Adds `target` prop to `Button` for use when passing a `url`.
- Marks the `external` prop on `Link` as deprecated. Fixes #106 
- Adds a `fullWidth` prop to `Link` and passes it through from `Button` to fix various styling issues. Fixes #107
None of these are breaking changes.

Fix issues with Button and Link

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/styles.css

Adds a `tabIndex` to modal content to be the initial focus and moves the close button to the end of content so that it remains in the tabbable items but at the end. Adds an accessibility label to the close button.
Also adds a focus ring to the base `button` style that was hiding this issue in the Playbook docs/sandbox.
Fixes #97

Fix Modal focusing close button on open

---

UNRELEASED.md
src/components/Avatar/Avatar.tsx
src/components/Logo/Logo.tsx

This PR removes an invalid "role='img'" declaration on the containing `<span>` inside both Logo + Avatar. The purpose of "role='img'" is generally to describe an image that's composed of multiple images, code samples, etc. and when it's included, it should have alt text. Since in this situation we're just showing a single image, and it's already aria compliant, this role unnecessary/invalid.
The reason this was discovered was that the automated accessibility tester on webpagetest.org marked it as a "serious" issue on some of our public pages.
Asana Link: https://app.asana.com/0/1205633609426968/1205837694200797/f
It's up on QA-8 (using a locally built version of Playbook)

Fix remove invalid aria role on logo

---

.gitignore
UNRELEASED.md
src/components/Avatar/Avatar.tsx
src/components/LazyImage/LazyImage.tsx
src/components/Logo/Logo.tsx

This PR introduces support for `srcSet` configurations on both LazyImage and Logo. It also fixes an invalid aria role on LazyImage. Lastly, .gitignore was updated to ignore IntelliJ (webstorm) project files during development.
Asana Link: https://app.asana.com/0/174985629888208/1205960258821029/f
There's a branch up on QA-8 built with a locally packed version of Playbook, featuring these updates.

Chore add srcset to logo

---

UNRELEASED.md
tailwind.preset.js

This PR updates the `font-bold` class to have a font weight of 600
https://app.asana.com/0/0/1206490214344430/f

Chore: update font bold to 600 weight

---

UNRELEASED.md
src/components/Modal/Modal.module.css
src/components/Modal/Modal.tsx

This PR bumps up the font size on `Modal` to 24px
https://app.asana.com/0/0/1206513433904250/f

Chore: make modal titles larger

---

UNRELEASED.md
src/components/Select/Select.module.css
src/components/TextInput/TextInput.module.css

This PR changes the font size to 16px for `Select` and `TextInput` components to avoid the iOS zoom issue.
https://app.asana.com/0/0/1206490214344426/f

Fix: set font size to text-body-lg on mobile for TextInput/Select

---

UNRELEASED.md
src/components/TextInput/TextInput.tsx

This PR adds `min`, `max`, and `step` props to `TextInput`.  
Resolves ([77](https://github.com/FieldLevel/FieldLevelPlaybook/issues/77))

Feature: add min/max/step props to TextInput

---

UNRELEASED.md
src/components/Modal/Modal.tsx

While migrating the new Recruiter Search experience, QA feedback came back requesting that we not "auto focus" any elements when the Modal dialog opens. That behavior is customizable via Radix/Dialog.Content, but we weren't supporting any way to configure that prop. This PR just opens up that possibility.

Chore: add onOpenAutoFocus prop to Modal

---

src/components/Link/Link.tsx

In order to use Radix.DropdownMenu with WiredLink, we need to pass a ref to Playbook.Link. This PR wraps Link in React.forwardRef

Chore: add ForwardRef to Link

---

UNRELEASED.md
docs/Overlays/Modal.mdx
docs/Overlays/Modal.stories.tsx
src/components/Modal/Modal.tsx

Introduces a new prop for `Modal` called `persistent` that hides the close button and prevents user interaction outside the modal and pressing the Escape key from automatically dismissing the Modal. This prop will default to `false` so existing `Modal` usage will be unaffected.

Feature: Introduce persistent mode for Modal

---

docs/Feedback/Feedback.mdx
docs/Feedback/Feedback.stories.tsx
src/components/Feedback/Feedback.module.css
src/components/Feedback/Feedback.tsx
tailwind.preset.js

Refactors the `Feedback` component to provide more flexibility with style and positioning and simplifies the standard design by deprecating `title`. These changes were made to allow using `Feedback` in more cases including the new `SystemToast` component we use for account switching. The biggest change is that the component is no longer responsive on it's own, it expects the consuming application to handle the responsibility of setting the `position` for different screen sizes. This isn't technically a breaking change but because the component won't position as it did before without application changes and because we started deprecating the `title` prop in this version, we are treating it as a breaking change.
Changes are as follows:
- Removes responsive styling and introduces four …

Feature: More customization for Feedback
